### ISSUE TITLE
Incorrect package.json "main" entry

### ISSUE THREAD

**Issue by svashish305** [bitpay/nodejs-bitpay-client#46] opened 2022-01-13 11:16 UTC
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/15891085/149320546-63e6c5d0-57af-4e53-889f-c09db6e3d230.png">

Other than linked PR below, Workaround to downgrade package version to "bitpay-sdk": "^1.4.2102"

**Comment by svashish305** [comment] 2022-01-13 12:06
#47 should fix this

**Comment by anbugal** [comment] 2022-01-26 12:03
Hi, we could not reproduce this issue but I suggest you try our testing package that includes a couple of changes that will be available in the next stable version. The testing package is called "bittest" and it's an acceptance copy of the official package:
https://www.npmjs.com/package/bittest

Here's an example of the two ways to initialise it:
```node
        const {Client, Env, Currency, Models, Tokens, Facade} = require('bitpay-sdk');
        ...
        
        let tokens = Tokens;

        tokens.merchant = 'MERCHANT_TOKEN';

        let keyPlainTextOrPathToKeyFile = 'PRIVATE_KEY_HEX_OR_PATH';

        let client = new Client(null, Env.Test, keyPlainTextOrPathToKeyFile, tokens);
        // OR
        let client = new Client("PATH_TO_FILE");
```

**Comment by jekh** [comment] 2022-01-26 17:57
This was fixed in #40

**Comment by svashish305** [comment] 2022-01-26 18:22
@anbugal @jekh I've done the integration with V1 package, which was workaround then as latest version, upon npm install, puts the script in path that is mismatching with the specified path in package.json therefore affecting users to import. Steps to reproduce is to install latest version 2.x from npm and try require bitpay sdk, which errors out.

**Comment by anbugal** [comment] 2022-01-27 11:54
Hi @svashish305 we're working on a new version that also replaces "request-native" and should solve this issue, could you please try it out? it is deployed to our testing package called "bittest"
https://www.npmjs.com/package/bittest

**Comment by svashish305** [comment] 2022-01-27 12:24
> Hi @svashish305 we're working on a new version that also replaces "request-native" and should solve this issue, could you please try it out? it is deployed to our testing package called "bittest" https://www.npmjs.com/package/bittest

Hi @anbugal, i replaced my version of bitpay-sdk with latest version of bittest and I'm able to instantiate client, create and retreive invoices. Would be great if this gets live soon so everyone can implement without any hassles.

**Comment by anbugal** [comment] 2022-01-31 10:41
@svashish305 you can now use the version 3.0.2202

**Closed by anbugal** 2022-01-31 10:41 UTC
